name: Test Lua with LuaRocks

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: leafo/gh-actions-lua@v11
        with:
          luaVersion: "5.1.5"

      - name: Setup LuaRocks
        uses: leafo/gh-actions-luarocks@v5
        with:
          luaRocksVersion: "3.11.1"

      - name: build
        run: |
          luarocks install busted
          luarocks install luafilesystem
          luarocks install dkjson
          luarocks install sha1

      - name: test update_lib_json.lua
        run: |
          busted ci/update_lib_json.lua -o utfTerminal
